---
language: java

jdk:
- oraclejdk8

node_js:
  - "4.1"

before_script:
- cd static/src && npm install && npm run build

script:
- ./gradlew clean --info
- ./gradlew build --info


after_success:
- ./gradlew jacocoTestReport coveralls